# Generated by Django 5.2.5 on 2025-08-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachingassistant',
            name='course',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
