# Generated by Django 5.2.5 on 2025-08-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_enrollment_student'),
        ('users', '0002_teachingassistant_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingassistant',
            name='course',
            field=models.ManyToManyField(blank=True, related_name='teaching_assistants', to='courses.course'),
        ),
    ]
