# Generated by Django 5.2.5 on 2025-08-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_chatme_room_id_466ea2_idx',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='file',
        ),
    ]
