# Generated by Django 5.2.5 on 2025-08-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('ma', 'makeup'), ('qu', 'quiz'), ('mi', 'midterm'), ('or', 'oral'), ('fi', 'final')], max_length=2),
        ),
    ]
