# Generated by Django 5.2.5 on 2025-08-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('qu', 'quiz'), ('or', 'oral'), ('mi', 'midterm'), ('ma', 'makeup'), ('fi', 'final')], max_length=2),
        ),
    ]
