# Generated by Django 5.2.5 on 2025-08-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_exam_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('or', 'oral'), ('mi', 'midterm'), ('fi', 'final'), ('qu', 'quiz'), ('ma', 'makeup')], max_length=2),
        ),
    ]
