# Generated by Django 5.2.5 on 2025-08-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_exam_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('mi', 'midterm'), ('fi', 'final'), ('or', 'oral'), ('qu', 'quiz'), ('ma', 'makeup')], max_length=2),
        ),
    ]
