# Generated by Django 5.2.5 on 2025-08-15 17:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_exam_exam_type'),
        ('users', '0003_alter_teachingassistant_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('fi', 'final'), ('qu', 'quiz'), ('mi', 'midterm'), ('ma', 'makeup'), ('or', 'oral')], max_length=2),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='examregistration',
            name='registration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterUniqueTogether(
            name='studentanswer',
            unique_together={('question', 'student')},
        ),
    ]
