# Generated by Django 5.2.5 on 2025-08-20 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_alter_exam_exam_type_alter_examquestion_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('qu', 'quiz'), ('or', 'oral'), ('ma', 'makeup'), ('mi', 'midterm'), ('fi', 'final')], max_length=2),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examquestion'),
        ),
    ]
