# Generated by Django 5.2.5 on 2025-08-07 16:38

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_enrollment_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.course_material_path),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='material_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('link', 'Link')], max_length=10),
        ),
    ]
