# Generated by Django 5.2.5 on 2025-08-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursematerial_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='url_or_path',
        ),
    ]
