# Generated by Django 5.2.5 on 2025-08-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_coursematerial_url_or_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
