# Generated by Django 5.2.5 on 2025-08-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_enrollment_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='post_date',
            new_name='announcement_date',
        ),
    ]
