# Generated by Django 5.2.5 on 2025-08-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_rename_post_date_announcement_announcement_date'),
        ('users', '0003_alter_teachingassistant_course'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('course', 'student'), name='uniq_course_student_enrollment'),
        ),
    ]
