# Generated by Django 5.2.5 on 2025-08-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
